## 1차원 array 인덱싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

np.int64(5)

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8]=12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## 2차원 array 인덱싱

In [11]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
# 2행의 전체 값 가져오기
arr2[2, :]

array([ 9, 10, 11, 12])

In [27]:
# 1행 ~ 2행 전체 값 가져오기
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# 전체 행을 가져오되, 마지막 열 값만 가져오기
arr2[:, 3]

array([ 4,  8, 12, 16])

In [25]:
arr2[:, -1]

array([ 4,  8, 12, 16])

In [29]:
# 0~1행까지 1~2열까지의 값만 가져오기
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

## boolean 인덱싱

In [30]:
names = np.array(['AAA','BBB','CCC','AAA','BBB','CCC','CCC'])
data = np.random.randn(7,4)

In [31]:
names

array(['AAA', 'BBB', 'CCC', 'AAA', 'BBB', 'CCC', 'CCC'], dtype='<U3')

In [32]:
data

array([[ 1.09788693,  0.49535526,  0.6307112 , -0.58374692],
       [ 1.07737489,  0.15919075,  2.25752229,  1.76860418],
       [ 2.18392893,  0.74520567,  0.29817694, -0.67246473],
       [-1.07914184,  0.40313872, -1.26673277, -0.82054145],
       [ 1.50466597,  1.46529842, -0.70855045,  0.45387607],
       [-1.36864456, -0.78835733,  0.20819799, -0.56955088],
       [-0.77157607, -0.70566394,  0.50552164,  0.22750803]])

### names array와 data array의 각 행에 순서대로 대응된다고 가정 인덱싱 진행

In [36]:
names =='CCC' # 값이 CCC인 성분의 위치에는 True, 그 외의 위치에는 False로 확인

array([False, False,  True, False, False,  True,  True])

In [44]:
data[names == 'CCC', :]

array([[ 2.18392893,  0.74520567,  0.29817694, -0.67246473],
       [-1.36864456, -0.78835733,  0.20819799, -0.56955088],
       [-0.77157607, -0.70566394,  0.50552164,  0.22750803]])

In [45]:
data[names == 'AAA', :]

array([[ 1.09788693,  0.49535526,  0.6307112 , -0.58374692],
       [-1.07914184,  0.40313872, -1.26673277, -0.82054145]])

In [47]:
# AAA또는 CCC의 마스크를 이용하여 array 인덱싱하기
data[(names == 'AAA') | (names == 'CCC'), :]

array([[ 1.09788693,  0.49535526,  0.6307112 , -0.58374692],
       [ 2.18392893,  0.74520567,  0.29817694, -0.67246473],
       [-1.07914184,  0.40313872, -1.26673277, -0.82054145],
       [-1.36864456, -0.78835733,  0.20819799, -0.56955088],
       [-0.77157607, -0.70566394,  0.50552164,  0.22750803]])

In [56]:
# 조건부 마스크
# 마지막 열에 대해서 0보다 작은 값 인덱싱
data[:, 3] < 0

array([False, False, False, False, False, False, False])

In [55]:
# 마지막 열에 대해서 0보다 작은 값의 행을 모두 1로 변경
data[data[:, 3] < 0, :] = 1

In [53]:
data

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.07737489,  0.15919075,  2.25752229,  1.76860418],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.50466597,  1.46529842, -0.70855045,  0.45387607],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.77157607, -0.70566394,  0.50552164,  0.22750803]])